universe                = docker
docker_image            = nvidia/cuda:11.4.3-runtime-ubuntu20.04
executable              = execute.sh

# Python file to run, can also include arguments
arguments               = demo2.py

# Paths to output, error, and log files
# Make sure all the parent directories exist
output                  = /home/hlcv_teamxxx/condor_logs/demo2.$(ClusterId).$(ProcId).out
error                   = /home/hlcv_teamxxx/condor_logs/demo2.$(ClusterId).$(ProcId).err
log                     = /home/hlcv_teamxxx/condor_logs/demo2.$(ClusterId).log

should_transfer_files   = YES

# Remove this when using interactive mode
when_to_transfer_output = ON_EXIT

request_GPUs = 1
request_CPUs = 1
request_memory = 3G
requirements = UidDomain == "cs.uni-saarland.de" 
+WantGPUHomeMounted = true
queue 1